AllCops:
  Exclude:
    - 'features/support/env.rb'
    - 'script/cucumber'
    - 'lib/tasks/cucumber.rake'
    - 'lib/tasks/auto_annotate_models.rake'
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'config/routes.rb'
    - 'config/initializers/suppress_minitest.rb'
    - 'config/initializers/devise.rb'
    - 'config/initializers/content_security_policy.rb'
    - 'config/initializers/backtrace_silencers.rb'
    - 'config/environments/production.rb'
    - 'config/application.rb'
    - 'config/spring.rb'
    - 'bin/**/*'
    - 'Gemfile'


Metrics/AbcSize:
  Exclude:
    - 'features/step_definitions/*_steps.rb'

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'

Metrics/LineLength:
  Max: 99
  Exclude:
    - 'features/step_definitions/*_steps.rb'

Style/Documentation:
  Exclude:
    - '**/*'

Style/EmptyMethod:
  Exclude:
    - '**/*'

Style/Encoding:
  Enabled: false
